language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=30
  - ANDROID_BUILD_TOOLS_VERSION=30.0.0
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_ABI=armeabi-v7a
  - QEMU_AUDIO_DRV=none

android:
  components:
    
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platform;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platform;android-$ANDROID_API_LEVEL"

before_script:
  - chmod +x gradlew
  #Emulator Instance
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_api/$ANDROID_ABI
  - emulator -avd test -no-window & #android-wait-for-emulator
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
 
#script:
#  - ./gradlew clean build
#  - ./gradlew test
